-- Personal prescription text suggestions for each doctor.
-- Stores only clinician-entered text (dose notation and meal/timing instruction).
-- No medicine-specific dose or timing is generated by this migration.

create extension if not exists pgcrypto;

create table if not exists public.prescription_text_suggestions (
  id uuid primary key default gen_random_uuid(),
  doctor_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('dose', 'meal_instruction')),
  text text not null check (length(btrim(text)) > 0),
  usage_count integer not null default 1 check (usage_count > 0),
  last_used_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (doctor_id, category, text)
);

create index if not exists prescription_text_suggestions_doctor_category_recent_idx
  on public.prescription_text_suggestions (doctor_id, category, last_used_at desc);

create index if not exists prescription_text_suggestions_doctor_category_usage_idx
  on public.prescription_text_suggestions (doctor_id, category, usage_count desc);

alter table public.prescription_text_suggestions enable row level security;

drop policy if exists "prescription text suggestions select own" on public.prescription_text_suggestions;
create policy "prescription text suggestions select own"
  on public.prescription_text_suggestions
  for select
  to authenticated
  using (doctor_id = auth.uid());

drop policy if exists "prescription text suggestions insert own" on public.prescription_text_suggestions;
create policy "prescription text suggestions insert own"
  on public.prescription_text_suggestions
  for insert
  to authenticated
  with check (doctor_id = auth.uid());

drop policy if exists "prescription text suggestions update own" on public.prescription_text_suggestions;
create policy "prescription text suggestions update own"
  on public.prescription_text_suggestions
  for update
  to authenticated
  using (doctor_id = auth.uid())
  with check (doctor_id = auth.uid());

drop policy if exists "prescription text suggestions delete own" on public.prescription_text_suggestions;
create policy "prescription text suggestions delete own"
  on public.prescription_text_suggestions
  for delete
  to authenticated
  using (doctor_id = auth.uid());

create or replace function public.record_prescription_text_suggestion(
  p_category text,
  p_text text
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_text text := btrim(coalesce(p_text, ''));
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if p_category not in ('dose', 'meal_instruction') then
    raise exception 'Unsupported suggestion category';
  end if;

  if v_text = '' then
    return;
  end if;

  insert into public.prescription_text_suggestions (
    doctor_id,
    category,
    text,
    usage_count,
    last_used_at
  )
  values (
    auth.uid(),
    p_category,
    v_text,
    1,
    now()
  )
  on conflict (doctor_id, category, text)
  do update set
    usage_count = public.prescription_text_suggestions.usage_count + 1,
    last_used_at = now();
end;
$$;

create or replace function public.search_prescription_text_suggestions(
  p_category text,
  p_search_term text default '',
  p_limit integer default 10
)
returns table (
  id uuid,
  text text,
  usage_count integer,
  last_used_at timestamptz
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    s.id,
    s.text,
    s.usage_count,
    s.last_used_at
  from public.prescription_text_suggestions s
  where s.doctor_id = auth.uid()
    and s.category = p_category
    and (
      btrim(coalesce(p_search_term, '')) = ''
      or s.text ilike '%' || btrim(p_search_term) || '%'
    )
  order by
    s.last_used_at desc,
    s.usage_count desc,
    s.text asc
  limit greatest(1, least(coalesce(p_limit, 10), 30));
$$;

grant select, insert, update, delete on public.prescription_text_suggestions to authenticated;
grant execute on function public.record_prescription_text_suggestion(text, text) to authenticated;
grant execute on function public.search_prescription_text_suggestions(text, text, integer) to authenticated;
